services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    build:
      context: requirements/mariadb
      args:
        - SQL_DATABASE
        - SQL_ROOT
        - SQL_ROOT_PASSWORD
        - SQL_USER
        - SQL_PASSWORD
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
      #ports:
      #- 3306:3306
    networks:
      - inception
    env_file: ".env"

  wordpress:
    build:  requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    networks:
      - inception
        #ports:
        #- 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/febonaer/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/febonaer/data/wordpress
