services:
  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - inception
    env_file: ".env"

  wordpress:
    build:  requirements/wordpress/
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/febonaer/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/febonaer/data/wordpress
